export type CommandType =
  | 'reg'
  | 'update_winners'
  | 'create_room'
  | 'add_user_to_room'
  | 'create_game'
  | 'update_room'
  | 'add_ships'
  | 'start_game'
  | 'attack'
  | 'randomAttack'
  | 'turn'
  | 'finish';

export type ShipType = 'small' | 'medium' | 'large' | 'huge';

export type AttackStatus = 'miss' | 'killed' | 'shot';

export type PlayerDataIn = {
  name: string;
  password: string;
};

export type PlayerDataOut = {
  name: string;
  index: number | string;
  error: boolean;
  errorText: string;
};

export type Winner = {
  name: string;
  wins: number;
};

export type Room = {
  indexRoom: string | number;
};

export type Game = {
  idGame: number | string;
  /**
   * generated by server id for player in the game session, not enemy (unique id for every player)
   */
  idPlayer: number | string;
};

export interface RoomUser {
  name: string;
  index: number | string;
}

export type RoomState = {
  roomId: number | string;
  roomUsers: RoomUser[];
};

export interface Ship {
  position: Position;
  direction: boolean;
  length: number;
  type: ShipType;
}

export type BaseGameData = {
  gameId: number | string;
  /**
   * id of the player in the current game session
   */
  indexPlayer: number | string;
};

export type Position = {
  x: number;
  y: number;
};

export type AddShipData = BaseGameData & {
  ships: Ship[];
};

export type StartGameData = {
  /**
   * player's ships, not enemy's
   */
  ships: Ship[];
  /**
   * id of the player in the current game session, who have sent his ships
   */
  currentPlayerIndex: number | string;
};

export type AttackInData = BaseGameData & Position;

export type GameSession = {
  /**
   * id of the player in the current game session
   */
  currentPlayer: number | string;
};

export type AttackOutData = GameSession & {
  position: Position;
  status: AttackStatus;
};

export type WinInfo = {
  /**
   * id of the player in the current game session
   */
  winPlayer: number | string;
};

export interface BaseMessage {
  type: CommandType;
  data: Record<string, unknown> | Record<string, unknown>[] | '';
  id: 0;
}

// Player

/**
 * Login or create player
 */
export interface RegPlayerInMsg extends BaseMessage {
  type: 'reg';
  data: PlayerDataIn;
}

export interface RegPlayerOutMsg extends BaseMessage {
  type: 'reg';
  data: PlayerDataOut;
}

/**
 * Update winners (for all after every winners table update)
 */
export interface UpdWinnersOutMsg extends BaseMessage {
  type: 'update_winners';
  data: Winner[];
}

// Room

/**
 * Create new room (create game room and add yourself there)
 */
export interface CreateRoomInMsg extends BaseMessage {
  type: 'create_room';
  date: '';
}

/**
 * Add user to room (add youself to somebodys room, then remove the room from available rooms list)
 */
export interface AddUserToRoomInMsg extends BaseMessage {
  type: 'add_user_to_room';
  data: Room;
}

/**
 * send for both players in the room, after they are connected to the room
 */
export interface CreateGameOutMsg extends BaseMessage {
  type: 'create_game';
  data: Game;
}

/**
 * Update room state (send rooms list, where only one player inside)
 */
export interface UpdateRoomOutMsg extends BaseMessage {
  type: 'update_room';
  data: RoomState[];
}

// Ships

/**
 * Add ships to the game board
 */
export interface AddShipInMsg extends BaseMessage {
  type: 'add_ships';
  data: AddShipData;
}

/**
 * Start game (only after server receives both player's ships positions)
 */
export interface StartGameOutMsg extends BaseMessage {
  type: 'start_game';
  data: StartGameData;
}

// Game

/**
 * Attack msg from client
 */
export interface AttackInMsg extends BaseMessage {
  type: 'attack';
  data: AttackInData;
}

/**
 * Attack feedback (should be sent after every shot, miss and after kill sent miss for all cells around ship too)
 */
export interface AttackOutMsg extends BaseMessage {
  type: 'attack';
  data: AttackOutData;
}

export interface RandomAttackInMsg extends BaseMessage {
  type: 'randomAttack';
  data: BaseGameData;
}

/**
 * Info about player's turn (send after game start and every attack, miss or kill result)
 */
export interface PlayerInfoOutMsg extends BaseMessage {
  type: 'turn';
  data: GameSession;
}

/**
 * Finish game
 */
export interface FinishGameOutMsg extends BaseMessage {
  type: 'finish';
  data: WinInfo;
}
